### ISSUE TITLE
Possible to get the same data for other channels?

### ISSUE THREAD

**Issue by greglandrum** [ContinuumIO/anaconda-package-data#6]
Firstly: this is a great data source. Thanks for providing it!

I'd love to be able to get the same type of data for a specific anaconda cloud channel that isn't one of the big ones (i.e. not anaconda, conda-forge, or bioconda) so that I can more easily track adoption by OS and Python version for the packages we distribute. Is there an API (or scripts) that I can use for this?

**Comment by seibert** [comment]
We have been hesitant to add all channels to the data files because there is a very long tail of channels, however we are happy to whitelist additional channels with the channel owner's permission.  Let us know which channel you want to see added, and we'll contact the email address associated with the channel admins to confirm permission.

**Comment by greglandrum** [comment]
@seibert sorry for the slow reply, this got buried under a bunch of other stuff.
The channel I'm interested in being able to do the historical stats data for is rdkit:
https://anaconda.org/rdkit
I am the owner of the channel, but I'm happy to get a confirmation email too.

**Comment by sophiamyang** [comment]
added rdkit channel
